# Generated by Django 3.1.3 on 2021-01-08 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caractere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Caractere',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nom_latin', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Espece',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Espece_caractere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(max_length=100)),
                ('caractere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cle.caractere')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cle.espece')),
            ],
        ),
    ]
