# Generated by Django 3.1.3 on 2021-01-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'cle',
                'ordering': ['nom'],
            },
        ),
    ]
