# Generated by Django 3.1.3 on 2021-01-08 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cle', '0002_cle'),
    ]

    operations = [
        migrations.AddField(
            model_name='espece',
            name='cle_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cle.cle'),
            preserve_default=False,
        ),
    ]
