# Generated by Django 3.1.3 on 2021-01-10 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cle', '0003_espece_cle_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caractere',
            options={'ordering': ['id'], 'verbose_name': 'Caractere'},
        ),
        migrations.CreateModel(
            name='Etat_caractères',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(max_length=100)),
                ('caractere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cle.caractere')),
            ],
            options={
                'verbose_name': 'Etat de Caractere',
            },
        ),
    ]
