# Generated by Django 3.1.3 on 2021-01-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cle', '0004_auto_20210110_1234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etat_caractères',
            new_name='Etat_caracteres',
        ),
    ]
